### PR TITLE
Add display id as parameter of the signed URL

### PR DESCRIPTION
**Pull request by andrecardoso**

### CODE REVIEW

**Comment by andrecardoso** [comment]
[(2) URL Provider adds display id to signed url](https://trello.com/c/ErZZyg01/4274-2-url-provider-adds-display-id-to-signed-url)

**Comment by tejohnso** [comment]
@stulees I worked with @andrecardoso on Friday to validate that and it worked out. I was worried that only the url that was signed would show up in the logs but the full client side url including signature shows up in the logs. I was also fairly certain that appending the display id would invalidate the signature, and that also turned out to be false. :+1:

**Comment by andrecardoso** [comment]
@stulees here: https://bigquery.cloud.google.com/results/avid-life-623:US.bquijob_580b8453_16316bc1490

**Comment by andrecardoso** [comment]
@tejohnso I manually tested it using the beta player and Chrome OS on Friday

**Pull request merged**
