### PR TITLE
Provide Rise Storage licensing status

### PR DESCRIPTION
**Pull request by stulees**
- RLS listens for CLIENT-LIST message and checks when licensing module is present. Upon being present, RLS broadcasts LICENSING-REQUEST
- RLS listens for LICENSING-UPDATE and handles updating authorization. If authorization is different from previously stored status, RLS broadcasts STORAGE-LICENSING-UPDATE with status through web socket
- RLS listens for STORAGE-LICENSING-REQUEST, handles by broadcasting STORAGE-LICENSING-UPDATE with authorization status through web socket

### CODE REVIEW

**Comment by tejohnso** [comment]
Why isn't this licensing functionality being handled in the licensing module?

**Comment by stulees** [comment]
@tejohnso We have common-display-module logic for modules that abstracts analysis of specific product authorization. Based on this I presumed modules are responsible for checking their respective license of their product (eg. Local Storage/Rise Storage, Twitter/RPP) and provide the authorization status to whatever client component requires it. 

If I understand you right, you're wondering why everything isn't centralized to just Licensing module and alleviate the necessity of individual modules needing to provide this. So far, we have designed as I described it above, but I'm not sure I see a major advantage doing it the way we have it.  @santiagonoguez Any thoughts here? Thanks

**Comment by santiagonoguez** [comment]
I agree it's not an easy decision where to leave this logic. I think this PR had priority in simplifying the browser code. And the alternative would be to change licensing-module so it provides more digested events 'rpp-license-status-update', 'storage-subscription-status-update' and so on.

**Comment by andrecardoso** [comment]
I like @santiagonoguez 's idea

**Comment by stulees** [comment]
@Rise-Vision/delivery  We're going to need to decide on this sooner than later as this PR was for Image/Video using RLS and Image/Video are going to need to listen for XXX message indicating storage subscription status. I'm weary in changing this now and losing the time invested in this PR. I think we should keep RLS as is and plan to centralize Licensing later. Thoughts?  @santiagonoguez You're most familiar with Licensing module, how much effort do you see in centralizing everything to just Licensing?

**Comment by santiagonoguez** [comment]
I agree it should be queued for later. I think it would be a 3 card.

**Pull request merged**
